- index.tsx
- package-lock.json
- package.json
- src/components/generic/data-chart.tsx
- src/components/generic/portfolio-fund-card.tsx
- src/components/providers/api-provider.tsx
- src/components/providers/funds-api-provider.tsx
- src/components/providers/portfolio-funds-api-provider.tsx
- src/components/providers/portfolios-api-provider.tsx
- src/components/screens/funds/funds-details-screen.tsx
- src/components/screens/funds/funds-list-screen.tsx
- src/components/screens/home/portfolio-screen.tsx
- src/components/screens/portfolio/my-funds-screen.tsx
- src/components/screens/portfolio/portfolio-context-provider.tsx
- src/components/screens/portfolio/portfolio-select.tsx
- src/components/screens/portfolio/statistics-screen.tsx
- src/localization/en.json
- src/localization/fi.json
- src/localization/strings.ts
- src/resources/test-data.tsx
- src/styles/screens/portfolio/my-funds-screen.ts
- src/styles/screens/portfolio/portfolio-select.ts
- src/styles/screens/portfolio/statistics-screen.ts
- src/types/index.ts
- src/utils/calculations.ts
- src/utils/chart.ts
> Feature 16 support for multiple portfolios

- package-lock.json
- package.json
- src/app/config.ts
- src/components/containers/auth-refresh.tsx
- src/components/providers/funds-api-provider.tsx
- src/components/screens/auth/login-required-screen.tsx
- src/components/screens/auth/strong-auth-view.tsx
- src/components/screens/auth/welcome-screen.tsx
- src/components/screens/funds/funds-details-screen.tsx
- src/components/screens/funds/funds-list-screen.tsx
- src/components/screens/home-screen.tsx
- src/components/screens/home/portfolio-screen.tsx
- src/features/auth/auth-slice.ts
- src/localization/en.json
- src/localization/fi.json
- src/localization/strings.ts
- src/types/config.ts
- src/types/index.ts
- src/types/navigators/auth.ts
- src/types/navigators/funds.ts
- src/types/navigators/home.ts
- src/types/navigators/root.ts
- src/utils/auth.ts
> Added support for anonymous user

- src/components/screens/portfolio/distributions-screen.tsx
- src/localization/en.json
- src/localization/fi.json
- src/localization/strings.ts
- src/styles/screens/portfolio/distribution-screen.ts
- src/types/index.ts
- src/utils/chart.ts
> Feature 31 distribution screen

- .gitmodules
- package.json
> Fixed the submodules issue

- package.json
- src/components/generic/data-chart.tsx
- src/components/providers/funds-api-provider.tsx
- src/components/providers/securities-api-provider.tsx
- src/components/screens/auth/strong-auth-view.tsx
- src/components/screens/auth/welcome-screen.tsx
- src/components/screens/funds/fund-details-screen.tsx
- src/components/screens/portfolio/statistics-screen.tsx
- src/components/screens/registration-screen.tsx
- src/components/screens/registration/language-selection-screen.tsx
- src/components/screens/settings-screen.tsx
- src/features/locale/locale-slice.ts
- src/localization/en.json
- src/localization/fi.json
- src/localization/strings.ts
- src/resources/test-data.tsx
- src/root.tsx
- src/styles/screens/funds/funds-details-screen.ts
- src/styles/screens/registration/language-selection-screen.tsx
- src/types/config.ts
- src/types/index.ts
- src/types/navigators/registration.ts
- src/types/navigators/root.ts
- src/utils/calculations.ts
- src/utils/chart.ts
Added language selection to initial login flow
> Fixed authentication issues

- src/components/screens/publications/publication-details-screen.tsx
- src/utils/injectables.ts
> Added fix for ios webview zoom

- src/components/generic/fund-card.tsx
- src/components/generic/portfolio-security-card.tsx
- src/components/screens/funds/active-funds-screen.tsx
- src/components/screens/funds/combination-funds-screen.tsx
- src/components/screens/funds/fund-details-screen.tsx
- src/components/screens/funds/interest-funds-screen.tsx
- src/components/screens/funds/passive-funds-screen.tsx
- src/components/screens/portfolio/statistics-screen.tsx
- src/styles/screens/funds/active-funds.ts
- src/styles/screens/funds/combination-funds.ts
- src/styles/screens/funds/funds-details-screen.ts
- src/styles/screens/funds/interest-funds.ts
- src/styles/screens/funds/passive-funds.ts
- src/styles/screens/portfolio/statistics-screen.ts
> android shadows clipping fix

- src/components/generic/fund-card.tsx
- src/components/generic/fund-details.tsx
- src/components/generic/portfolio-security-card.tsx
- src/components/generic/transactions-card.tsx
- src/components/screens/portfolio/distributions-screen.tsx
- src/components/screens/portfolio/transaction-details-screen.tsx
- src/types/index.ts
- src/utils/calculations.ts
- src/utils/chart.ts
- src/utils/injectables.ts
> euro sign and decimal separator

- src/components/generic/radio-button-option-item.tsx
- src/components/screens/auth/keycloak-login-screen.tsx
- src/components/screens/auth/login-required-screen.tsx
- src/components/screens/auth/welcome-screen.tsx
- src/components/screens/authentication-screen.tsx
- src/components/screens/funds/fund-details-screen.tsx
- src/components/screens/home/portfolio-screen.tsx
- src/components/screens/settings-screen.tsx
- src/localization/en.json
- src/localization/fi.json
- src/localization/strings.ts
- src/root.tsx
- src/styles/screens/auth/login-screen.ts
- src/types/config.ts
> Feature 73 login flow changes

- src/components/screens/portfolio/distributions-screen.tsx
- src/localization/en.json
- src/localization/fi.json
- src/localization/strings.ts
- src/localization/sv.json
- src/styles/screens/portfolio/distribution-screen.ts
- src/theme/index.ts
- src/theme/types.ts
- src/types/index.ts
- src/utils/generic.ts
> distribution screen show risk button

- src/generated/client/models/LocalizedValue.ts
> Bumped spec

- src/components/screens/auth/keycloak-login-screen.tsx
- src/components/screens/auth/login-required-screen.tsx
- src/components/screens/home-screen.tsx
- src/components/screens/home/portfolio-screen.tsx
- src/components/screens/settings-screen.tsx
- src/features/auth/auth-slice.ts
- src/root.tsx
Fixed more login issues
Resolves: #76
> Fixed application language change

- App.tsx
- package-lock.json
- package.json
- src/components/generic/transactions-card.tsx
- src/components/screens/funds/active-funds-screen.tsx
- src/components/screens/funds/combination-funds-screen.tsx
- src/components/screens/funds/interest-funds-screen.tsx
- src/components/screens/funds/passive-funds-screen.tsx
- src/components/screens/portfolio/transaction-details-screen.tsx
- src/components/screens/publications/publications-list-screen.tsx
- src/components/screens/publications/publications-list.tsx
- src/components/screens/settings-screen.tsx
- src/localization/en.json
- src/localization/fi.json
- src/localization/strings.ts
- src/localization/sv.json
- src/root.tsx
- src/utils/funds.ts
- src/utils/generic.ts
- src/utils/injectables.ts
- Back button from settings screen after language has been changed now somewhat works.
- Virtual bar code now has correct currency amount
- transaction type "security" now has target security name
> Feature 99 fixes to version 4

- App.tsx
- src/components/generic/fund-card.tsx
- src/components/generic/fund-details.tsx
- src/components/generic/history-value-chart.tsx
- src/components/generic/portfolio-security-card.tsx
- src/components/generic/transactions-card.tsx
- src/components/providers/meetings-api-provider.tsx
- src/components/providers/portfolios-api-provider.tsx
- src/components/providers/securities-api-provider.tsx
- src/components/screens/funds/fund-details-screen.tsx
- src/components/screens/funds/subscription-settings-screen.tsx
- src/components/screens/meeting/meeting-times-screen.tsx
- src/components/screens/meeting/new-meeting-screen.tsx
- src/components/screens/portfolio/my-security-details-screen.tsx
- src/components/screens/portfolio/transaction-details-screen.tsx
- src/features/locale/locale-slice.ts
- src/localization/en.json
- src/localization/fi.json
- src/localization/strings.ts
- src/localization/sv.json
- src/types/index.ts
- src/utils/calculations.ts
- src/utils/funds.ts
- src/utils/injectables.ts
> Feature 109 fixes to version 5

- src/components/containers/auth-refresh.tsx
- also added a login try to anonymous token if refresh fails
Resolves #111
> added check for offline token

- src/app/hooks.ts
- src/components/providers/portfolio-provider.tsx
- src/components/screens/auth/login-required-screen.tsx
- src/components/screens/portfolio/statistics-screen.tsx
- src/components/screens/settings-screen.tsx
- added fix for error in listing portfolios when user logs out and another user logs in without closing the app in between
> Feature 113 fixes to public release

- App.tsx
> Feature 124 automatic updates

- src/utils/chart.ts
> remove initial zeros

- src/components/providers/companies-api-provider.tsx
- src/components/providers/company-provider.tsx
- src/components/providers/portfolio-provider.tsx
- src/components/providers/portfolios-api-provider.tsx
- src/components/screens/portfolio/company-select.tsx
- src/components/screens/portfolio/portfolio-select.tsx
- src/generated/client/apis/CompaniesApi.ts
- src/generated/client/apis/PortfoliosApi.ts
- src/types/index.ts
- src/utils/my-securities.ts
> updated list company API call

- src/components/generic/history-value-chart.tsx
- src/components/screens/portfolio/company-select.tsx
- src/components/screens/portfolio/distributions-screen.tsx
- src/components/screens/portfolio/portfolio-select.tsx
- src/styles/screens/portfolio/company-select.ts
- src/utils/chart.ts
> Feature 135 company portfolio fix

- App.tsx
> fixed status bar visibility

- src/components/providers/portfolio-provider.tsx
- src/components/screens/portfolio/company-select.tsx
- src/components/screens/portfolio/portfolio-select.tsx
- src/types/index.ts
> added company portfolios

- src/components/screens/portfolio/company-select.tsx
- src/components/screens/portfolio/portfolio-select.tsx
- src/components/screens/portfolio/statistics-screen.tsx
> Bugfix 142 portfolios and companies can be selected while loading

- app.config.ts
- src/components/providers/portfolio-provider.tsx
- src/components/screens/portfolio/company-select.tsx
- src/components/screens/portfolio/portfolio-select.tsx
- src/components/screens/portfolio/statistics-screen.tsx
- src/components/screens/settings-screen.tsx
- src/types/index.ts
> Feature 137 save portfolio scr

- src/components/generic/portfolio-security-card.tsx
- src/generated/client/models/PortfolioSecurity.ts
> added portfolio securities rate date

- src/components/providers/portfolios-api-provider.tsx
- src/generated/client/apis/PortfoliosApi.ts
> Added support for versioned portfolios list

- src/components/screens/funds/subscription-settings-screen.tsx
- src/types/index.ts
- src/utils/generic.ts
- src/utils/portfolio-utils.ts
> Fixed issue with invalid reference code in subscription barcode

- package-lock.json
- package.json
> Hotfix 157 expo update version

- src/components/screens/funds/subscription-settings-screen.tsx
- src/localization/en.json
- src/localization/fi.json
- src/localization/strings.ts
- src/localization/sv.json
> Improved subscription screen UX
